Kilka testów
baktrius/MIMUW_PW_2nd_lab_assignment pull request #13
Opened 2023-12-30 17:23 UTC by adespawn

Testy extended_* poszerzają istniejące test próbując wyłapać dodatkowe przypadki brzegowe.
Testy send_recv_1.self oraz reasonable_sized_data.self sprawdzają w bezpośredni sposób przesyłanie dużych wiadomości
Test order_of_msg.self sprawdza czy program spełnia: ``MIMPI_Recv zwracać pierwszą (ze względu na czas przyjścia) wiadomość``
Test just_the_correct_msg.self sprawdza czy program odbiera wiadomość o wskazanej wielkości i wskazanym tagu
Test lot_of_messages.self jest testem wydajnościowym, jednak może sprawiać drobne problemy przy uruchamianiu (w szczególności może działać dłużej niż dany limit 200s)

2023-12-30 19:05 UTC, adespawn commented
Zapomniałem tego uwzględnić w testach, ale extended_deadlock warto uruchomić kilka - kilkanaście razy, jako że mogą tu istnieć różne przeploty które ciężko wyłapać w inny sposób

2024-01-01 15:50 UTC, C10udburst commented on examples/extended_deadlock.c
> +        int res2 = setenv(READ_VAR, "100", true);
Cyt. z [forum Moodle](https://moodle.mimuw.edu.pl/mod/forum/discuss.php?d=9393#p20065):
> [...] dajemy większe gwarancje. Mianowicie opóźnienie może dotyczyć jedynie funkcji chsend (chrecv nie będzie opóźniane w testach)

2024-01-01 15:56 UTC, adespawn commented on examples/extended_deadlock.c
> +        int res2 = setenv(READ_VAR, "100", true);
Celem sleepa w tym przypadku jest zwiększenie prawdopodobieństwa pewnych przeplotów, które w innych przypadkach miałby by niewielkie, ale ciągle niezerowe, prawdopodobieństwo. Wydaje mi się że w sytuacji gdy nie jest sprawdzana efektywność programów, takie rozwiązanie w testach nie powinno powodować problemów.

2024-01-06 11:14 UTC, wprzytula requested changes

2024-01-06 11:14 UTC, wprzytula commented on examples/extended_deadlock.c
> +    return 0;
Powinno być `return test_success()`.
W przeciwnym razie test nie przechodzi.

2024-01-06 21:01 UTC, baktrius reviewed
Fajne szczegółowe testy. Dodałem kilka sugestii. Merge jest do ustalenia z Wojtkiem - jak mi powie to go zrobię.
Ostatnia globalna sugestia - to treść PR'a (komentarz) można dodać jako README.md do katalogu tests/sc/

2024-01-06 21:08 UTC, adespawn commented on tests/sc/reasonable_sized_data.self
> +./run_test 30s 3 ./examples_build/send_any_size 2147483647 0 1
Zamysłem tego testu nie jest sprawdzanie wydajności programu, ale poprawności. 2GB to nie jest aż tak dużo, a jest to maksymalna wartość jaką można zgodnie ze specyfikacją wysłać przez bibliotekę.

2024-01-06 21:09 UTC, wprzytula commented
Myślę, że jakoś powinniśmy jasno rozdzielić testy "obowiązujące" od testów "opcjonalnych", czyli te, które poprawne rozwiązanie powinno przechodzić od tych, które niekoniecznie musi.

2024-01-06 21:13 UTC, wprzytula commented on tests/sc/reasonable_sized_data.self
> +./run_test 30s 3 ./examples_build/send_any_size 2147483647 0 1
Timeout 30s na ten test wydaje mi się spokojnie wystarczający @baktrius.

2024-01-06 21:24 UTC, adespawn commented on examples/all_my_file_desc.c
> +    for (int i = 1024; i < max_fd; i++)
Z tego co sprawdzałem u siebie eksperymentalnie, to dla wartości >1024 pojawiają się problemy. Zostawiłem to jednak, gdyby ktoś chciał się z tym pobawić.

2024-01-07 10:36 UTC, baktrius commented on examples/all_my_file_desc.c
> +    for (int i = 1024; i < max_fd; i++)
Ok

2024-01-07 10:50 UTC, merged